from fastapi import APIRouter, Depends, Query
from typing import List, Optional
from database.repository import DatabaseRepository
from api.dependencies import get_repository
from api.schemas import RecommendationResponse, RiskSummaryResponse

router = APIRouter(tags=["Intelligence"])

@router.get("/recommendations", response_model=List[RecommendationResponse])
async def get_recommendations(
    node_id: Optional[int] = None,
    limit: int = Query(50, le=500),
    repo: DatabaseRepository = Depends(get_repository)
):
    """Retrieve historical recommendations generated by OrchardBrain."""
    recs = await repo.get_recommendations(node_id=node_id, limit=limit)
    return recs

@router.get("/risk-summary", response_model=List[RiskSummaryResponse])
async def get_risk_summary(
    node_id: Optional[int] = None,
    limit: int = Query(50, le=500),
    repo: DatabaseRepository = Depends(get_repository)
):
    """Retrieve historical risk summaries."""
    risks = await repo.get_risk_summary(node_id=node_id, limit=limit)
    return risks
