"""Schema expansion

Revision ID: b40f64e0d455
Revises: 
Create Date: 2026-06-15 20:41:37.072025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40f64e0d455'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_history',
    sa.Column('command_id', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('actuator_type', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.create_table('infrastructure_metrics',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('tank_level', sa.Float(), nullable=True),
    sa.Column('fertilizer_tank_level', sa.Float(), nullable=True),
    sa.Column('pump_status', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'node_id')
    )
    op.create_table('node_status',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('battery_pct', sa.Integer(), nullable=False),
    sa.Column('uptime_sec', sa.Integer(), nullable=False),
    sa.Column('fw_version', sa.Integer(), nullable=False),
    sa.Column('sensor_mask', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('orchard_health',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('water_stress', sa.Integer(), nullable=False),
    sa.Column('nutrient_stress', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('time', 'node_id')
    )
    op.create_table('sensor_readings',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('soil_moisture', sa.Float(), nullable=False),
    sa.Column('ec', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('leaf_wetness', sa.Float(), nullable=True),
    sa.Column('solar_radiation', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('sensor_mask', sa.Integer(), nullable=False),
    sa.Column('battery_pct', sa.Integer(), nullable=False),
    sa.Column('tx_reason', sa.Integer(), nullable=False),
    sa.Column('rssi_last_rx', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'node_id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['time', 'node_id'], ['orchard_health.time', 'orchard_health.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['time', 'node_id'], ['orchard_health.time', 'orchard_health.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risks')
    op.drop_table('recommendations')
    op.drop_table('system_events')
    op.drop_table('sensor_readings')
    op.drop_table('orchard_health')
    op.drop_table('node_status')
    op.drop_table('infrastructure_metrics')
    op.drop_table('command_history')
    # ### end Alembic commands ###
